## Introduction

Data Prepration and Setup, preparing image data.

## Setup

In [1]:
import os
import pandas as pd

## Images, Directories and Labels

In [2]:
labels_2019 = pd.read_csv("../../data/2019/ISIC_2019_Training_GroundTruth.csv")
labels_2019.head()

          image  MEL  NV  BCC  AK  BKL  DF  VASC  SCC
0  ISIC_0000000    0   1    0   0    0   0     0    0
1  ISIC_0000001    0   1    0   0    0   0     0    0
2  ISIC_0000002    1   0    0   0    0   0     0    0
3  ISIC_0000003    0   1    0   0    0   0     0    0
4  ISIC_0000004    1   0    0   0    0   0     0    0

In [4]:
labels_2019['image'] = labels_2019['image'].apply(lambda name: name+"_2019.jpg")

In [6]:
labels_2019.head()

                   image  MEL  NV  BCC  AK  BKL  DF  VASC  SCC
0  ISIC_0000000_2019.jpg    0   1    0   0    0   0     0    0
1  ISIC_0000001_2019.jpg    0   1    0   0    0   0     0    0
2  ISIC_0000002_2019.jpg    1   0    0   0    0   0     0    0
3  ISIC_0000003_2019.jpg    0   1    0   0    0   0     0    0
4  ISIC_0000004_2019.jpg    1   0    0   0    0   0     0    0

In [7]:
labels_2019.to_csv("../../data/2019/ISIC_2019_Training_GroundTruth_2019.csv")